# Generated by Django 3.2.12 on 2022-03-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='app_type',
            new_name='room_class',
        ),
    ]
