# Generated by Django 3.2.12 on 2022-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20220313_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='options',
            field=models.ManyToManyField(related_name='hotels', to='hotels.Option', verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/hotels/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
    ]
