# Generated by Django 3.2.12 on 2022-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_room_room_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/hotels/', verbose_name='Фото'),
        ),
    ]
