# Generated by Django 3.2.12 on 2022-03-20 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0005_auto_20220313_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/countries/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='town',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.get_upload_to_hotel, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.get_upload_to_room, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='town',
            name='title',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Редакция')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel', verbose_name='Отель')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel', verbose_name='Отель')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.room', verbose_name='Отель')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
