# Generated by Django 3.2.12 on 2022-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20220321_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True, verbose_name='Дата заезда'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True, verbose_name='Дата отъезда'),
        ),
    ]
