# Generated by Django 3.2.12 on 2022-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
    ]
