# Generated by Django 3.2.12 on 2022-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_auto_20220404_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
