# Generated by Django 3.2.12 on 2022-04-27 16:55

from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_reservation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.PositiveSmallIntegerField(verbose_name='Категория (звездность)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.get_upload_to_hotel, verbose_name='Фотография отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.get_upload_to_room, verbose_name='Фотография номера'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ночь'),
        ),
    ]
