# Generated by Django 3.2.12 on 2022-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Текст отзыва'),
        ),
    ]
