# Generated by Django 3.2.12 on 2022-05-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='hotels.country', verbose_name='Страна'),
        ),
    ]
