# Generated by Django 3.2.12 on 2022-06-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_town_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.town', verbose_name='Город'),
        ),
    ]
